spring:
  datasource:
    url: ${NOTIFICATION_DB_URL}
    username: ${NOTIFICATION_DB_USER}
    password: ${NOTIFICATION_DB_PASSWORD}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
brevo:
  api-key: ${BREVO_API_KEY}
notification:
  email:
    enabled: ${EMAIL_ENABLED}
    from: ${NOTIFICATION_FROM_EMAIL}
    reply-to: ${NOTIFICATION_REPLY_TO}
  sms:
    enabled: ${SMS_ENABLED}
  push:
    enabled: ${PUSH_ENABLED}
