spring:
  datasource:
    url: jdbc:postgresql://blubug.me:8006/bakery_notifications
    username: notification_user
    password: notification_password
  mail:
    username: your-email@gmail.com
    password: your-app-password
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
brevo:
  api-key: your-brevo-api-key
notification:
  email:
    enabled: ${EMAIL_ENABLED}
    from: noreply@shahs-bakery.com
    reply-to: support@shahs-bakery.com
  sms:
    enabled: false
  push:
    enabled: false
